# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Als Johnstone
email: alsjohnstone@gmail.com
description: >
  Digital analyst, GTM enthusiast and R rookie.
logo: "/assets/images/bar-chart.gif"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Als Johnstone'
bio: >
  Digital analyst, GTM enthusiast and R rookie.
author_image: "/assets/images/bar-chart.gif"
twitter_username: alsjohnstone
github_username:  alsjohnstone

# Google Analytics
analytics_id: "UA-70159337-7"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  
highlighter: rouge
