---
title: Alistair Johnstone | Web Analytics Developer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: alsjohnstone@gmail.com
description: I like data and making things with with JavaScript, R, Python and Google
  Cloud Platform
logo: "/assets/images/bar-chart.gif"
baseurl: 
url: http://alsjohnstone.com
paginate: 5
post_dirs: false
name: alsjohnstone
bio: I like data and making things with with JavaScript, R, Python and Google Cloud
  Platform
author_image: "/assets/images/bar-chart.gif"
github_username: alsjohnstone
analytics_id: UA-70159337-7
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
- jekyll-paginate
highlighter: rouge
